# Generated by Django 5.2.5 on 2025-10-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='default_profile.png', upload_to='profile_images/'),
        ),
    ]
